### ISSUE TITLE
Add github actions support

### ISSUE THREAD

**Issue by netserf** [ahanaahluwalia/gcp-certified-associate-cloud-engineer#1]
Let's add some GitHub Actions support for basic link checking and markdown linting.

**Comment by netserf** [comment]
Submitted PR https://github.com/ahanaahluwalia/gcp-certified-associate-cloud-engineer/pull/2 to address this issue.

**Comment by ahanaahluwalia** [comment]
Completed in https://github.com/ahanaahluwalia/gcp-certified-associate-cloud-engineer/pull/3
